# Generated by Django 3.1 on 2020-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytoproductattributerelation',
            name='show_at_product_page',
            field=models.BooleanField(default=True, verbose_name='show at product page'),
        ),
    ]
