# Generated by Django 3.1 on 2020-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categorytoproductattributerelation_show_at_product_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icecat_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='icecat id'),
        ),
    ]
