# Generated by Django 3.1 on 2020-10-30 08:13

import catalog.models.products
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=catalog.models.products.ProductImage._get_images_upload_path, verbose_name='image'),
        ),
    ]
