# Generated by Django 3.1 on 2020-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_icecat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytoproductattributerelation',
            name='include_in_full_text_index',
            field=models.BooleanField(default=True, help_text='include in full text index', verbose_name='full text'),
        ),
    ]
