# Generated by Django 3.1 on 2020-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201030_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='external',
            field=models.URLField(blank=True, null=True, verbose_name='external image url'),
        ),
    ]
