# Generated by Django 3.1 on 2020-09-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categorytoproductattributerelation_include_in_full_text_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='icecat_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='icecat id'),
        ),
        migrations.AddField(
            model_name='brand',
            name='icecat_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='icecat id'),
        ),
        migrations.AddField(
            model_name='category',
            name='icecat_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='icecat id'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='icecat_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
