# Generated by Django 3.1 on 2020-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200902_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='description at english'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='image url'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=200, verbose_name='name at english'),
            preserve_default=False,
        ),
    ]
