# Generated by Django 3.1 on 2020-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200903_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('icecat_id', models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='icecat id')),
            ],
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='icecat_id',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='icecat id'),
        ),
    ]
