# Generated by Django 3.1 on 2020-09-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200904_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printstore_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='PrintStore id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='PrintStore profile id'),
        ),
    ]
