# Generated by Django 3.1 on 2020-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200904_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='str_value',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='string value'),
        ),
        migrations.AlterField(
            model_name='slotattributevalue',
            name='str_value',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='string value'),
        ),
    ]
