"""
Django settings for unicat project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

DEBUG_DEVELOPE = True
DEBUG_PROD = False

DEBUGS = {
    #'TRACE',
    #'Product.search',
    #'Product.get_attribute_groups',
    #'CategoryView',
}

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
PROJECT_ROOT = BASE_DIR
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')

DEVELOPE = str(BASE_DIR)[0] != '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&@u3-mue+egfd4c^*rrc&$q7h1^z-7xv6@&@%=@t&ukmp(63n3'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = DEBUG_DEVELOPE if DEVELOPE else DEBUG_PROD

ALLOWED_HOSTS = [
    '127.0.0.1', '127.0.0.1:8000', 'msklyarov.beget.tech', 'unicat.loc', 'unicat.loc:8000'
]

INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_tools',
    'django_utils',
    'django_extensions',
    'debug_toolbar',
    'easy_thumbnails',
    'rosetta',

    'website',
    'catalog'
]

MIDDLEWARE = [
    'website.middleware.StatsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'catalog.middleware.UrlMapperMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'unicat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'unicat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


if DEVELOPE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'db-unicat',
            'USER': 'db-unicat',
            'CONN_MAX_AGE': 3600,
            'PASSWORD': '111',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.sqlite3',
    #         'NAME': BASE_DIR / 'db.sqlite3',
    #     }
    # }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'msklyarov_db',
            'USER': 'msklyarov_db',
            #'CONN_MAX_AGE': 3600,
            'PASSWORD': 'd33ssaNAsadw2aV0xpFPm',
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }




# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('ru', 'Русский'),
    ('en', 'English'),
)

LANGUAGES_ADMIN = {
    'ru': 'Русский',
    'en': 'English',
}

# LOCALE_PATHS = (
#     os.path.join(BASE_DIR, 'locale/'),
# )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue'
        }
    },
    'formatters': {
        'main_formatter': {
            'format': '%(levelname)s:%(name)s: %(message)s '
                      '(%(asctime)s; %(filename)s:%(lineno)d)',
            'datefmt': "%Y-%m-%d %H:%M:%S",
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'main_formatter',
        },
        'production_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/production.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
            'filters': ['require_debug_false'],
        },
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
            'filters': ['require_debug_true'],
        },
        'hashtags_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/hashtags.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
        },
        'mail_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/mail.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
        },
        'django_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
        },
        'requests_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/requests.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
        },
        'warnings_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/warning.log'),
            'maxBytes': 1024 * 1024 * 50,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
            'filters': ['require_debug_true'],
        },
        'null': {
            'class': 'logging.NullHandler',
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'console', 'requests_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'level': 'WARNING',
            'handlers': ['django_file', ],
        },
        'py.warnings': {
            'handlers': ['warnings_file', ],
        },
        'hashtags': {
            'level': "ERROR",
            'handlers': ['console', 'production_file', 'debug_file', 'hashtags_file'],
        },
        'mail': {
            'level': "DEBUG",
            'handlers': ['console', 'production_file', 'debug_file', 'mail_file'],
        },
        '': {
            'handlers': ['console', 'production_file', 'debug_file'],
            'level': "DEBUG",
        },
    }
}

THUMBNAIL_ALIASES = {
    '': {
        'admin':  {'size': (200, 200), 'crop': False},

        'product_tiny': {'size': (80, 80), 'crop': False, 'bw':False, 'background':0xFFFFFF},
        'product_small': {'size': (160, 160), 'crop': False, 'bw':False, 'background':0xFFFFFF},

        # 'portfolio.tiny':  {'size': (80, 60), 'crop': True},
        # 'portfolio.front':  {'size': (372, 361), 'crop': True},
        # 'portfolio.pc':   {'size': (1024, 768), 'crop': False},
        # 'portfolio.pod':   {'size': (600, 800), 'crop': False},
        # 'portfolio.phone':   {'size': (450, 800), 'crop': True},
        #
        # 'design.admin':  {'size': (200, 400), 'crop': "0,0"},
        # 'design.admin_list':  {'size': (150, 200), 'crop': "0,0"},
        # 'design.small':  {'size': (200, 600), 'crop': "0,0"},
        # 'design.big':  {'size': (2000, 2000), 'crop': "0,0"},
        #
        #
        # 'tip.big': {'size': (1600, 1600), 'crop': False},
        #
        # 'service.big': {'size': (800, 800), 'crop': False},
        # 'service.small': {'size': (400, 400), 'crop': False},
        # 'service.tiny': {'size': (200, 200), 'crop': False},
        # 'service.thumb': {'size': (100, 100), 'crop': False},
        #
        # 'tarif.big': {'size': (800, 800), 'crop': False},
        # 'tarif.small': {'size': (400, 400), 'crop': False},
        # 'tarif.tiny': {'size': (200, 200), 'crop': False},
        # 'tarif.thumb': {'size': (100, 100), 'crop': False},

        # 'logo':  {'size': (300, 46), 'crop': False},
        #
        # 'xxlogo': {'size': (200, 250), 'crop': True},
        # 'xxthumb': {'size': (200, 200), 'crop': True},
        # 'xxbig':  {'size': (600, 600), 'crop': False},
        # 'xxsmall':  {'size': (100, 100), 'crop': True},
        #
        # 'news.thumb':  {'size': (370, 270), 'crop': True},
        # 'news.full':  {'size': (770, 562), 'crop': True},
        #
        # 'staff.thumb':  {'size': (270, 270), 'crop': True},
        # 'staff.full':  {'size': (550, 550), 'crop': True},
        # 'staff.sert':  {'size': (270, 270), 'crop': False},
        #
        # 'slade_background': {'size' :(1920, 750), 'crop': True},
        # 'content_image': {'size' :(550, 550), 'crop': True},
        #
        # 'website.page_thumb': {'size' :(270, 270), 'crop': True},
        # 'website.page_full': {'size' :(1170, 550), 'crop': True},
        # 'website.testimonial': {'size' :(116, 116), 'crop': True},
        #
        # 'gallery.full':     {'size': (1200, 1200), 'crop': False},
        # 'gallery.thumb.s':  {'size': (270, 270), 'crop': True},
        # 'gallery.thumb.h':  {'size': (370, 270), 'crop': True},
        # 'gallery.thumb.v':  {'size': (270, 370), 'crop': True},
        #
        # 'gvp':{'size': (500, 500), 'crop': False},
    },
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
    'easy_thumbnails.processors.background',
)

DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000
